In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

import seaborn as sns
sns.set()


import my_resample as ms
import my_functions as mf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

# from sklearn.ensemble.partial_dependence import plot_partial_dependence
# from sklearn.model_selection import GridSearchCV

# from sklearn.model_selection import KFold
# from sklearn.metrics import roc_curve, auc
# from scipy import interp
# from random import *
# import matplotlib.pyplot as plt
# %matplotlib inline

# from sklearn.ensemble.partial_dependence import plot_partial_dependence
# from sklearn.ensemble.partial_dependence import partial_dependence

from importlib import reload

import warnings
warnings.filterwarnings('ignore')

In [3]:
# directory
data_file_path = "/Users/gandalf/Documents/coding/do_not_commit/capstone/"
website_file_path = '/Users/gandalf/Documents/coding/rczyrnik.github.io/capstone/'

# READ IN DATA

In [4]:
X =  pd.read_pickle(data_file_path+'X.pkl')
y1 =  pd.read_pickle(data_file_path+'y1.pkl')
y2 =  pd.read_pickle(data_file_path+'y2.pkl')

In [5]:
X.head()

first_message_len  first_message_day_of_year  \
02sjTzcsaO02omVxM8Xm                  4                        254   
07lVtClAEQ01iDVeaXl1                 62                        249   
0AFU6guKDt01iDVeaXl1                 18                        249   
0AFU6guKDt01mfWG4vUm                 54                        184   
0AFU6guKDt06y5iMXoCP                 66                        184   

                      first_message_day_of_month  first_message_day_of_week  \
02sjTzcsaO02omVxM8Xm                          11                          1   
07lVtClAEQ01iDVeaXl1                           6                          3   
0AFU6guKDt01iDVeaXl1                           6                          3   
0AFU6guKDt01mfWG4vUm                           3                          1   
0AFU6guKDt06y5iMXoCP                           3                          1   

                      first_message_hour  const2  gender_sender  \
02sjTzcsaO02omVxM8Xm                   2       1            1.0   
07lVtClAEQ01iDVeaXl1                  20       1            0.0   
0AFU6guKDt01iDVeaXl1                  20       1            0.0   
0AFU6guKDt01mfWG4vUm                  20       1            0.0   
0AFU6guKDt06y5iMXoCP                  20       1            0.0   

                      inRelationship_sender  isClean_sender  isNight_sender  \
02sjTzcsaO02omVxM8Xm                    0.0             1.0             1.0   
07lVtClAEQ01iDVeaXl1                    1.0             1.0             1.0   
0AFU6guKDt01iDVeaXl1                    1.0             1.0             1.0   
0AFU6guKDt01mfWG4vUm                    0.0             1.0             0.0   
0AFU6guKDt06y5iMXoCP                    0.0             1.0             0.0   

                           ...        same_country  same_college  same_metro  \
02sjTzcsaO02omVxM8Xm       ...                   0             0           0   
07lVtClAEQ01iDVeaXl1       ...                   0             0           1   
0AFU6guKDt01iDVeaXl1       ...                   0             0           0   
0AFU6guKDt01mfWG4vUm       ...                   0             0           1   
0AFU6guKDt06y5iMXoCP       ...                   0             0           1   

                      overlap_roommate  overlap_hobbies  overlap_amenities  \
02sjTzcsaO02omVxM8Xm                 1                8                  0   
07lVtClAEQ01iDVeaXl1                 0                7                  3   
0AFU6guKDt01iDVeaXl1                 1                4                  2   
0AFU6guKDt01mfWG4vUm                 0                3                  1   
0AFU6guKDt06y5iMXoCP                 0                3                  1   

                      overlap_rent   distance  urgency_receiver  \
02sjTzcsaO02omVxM8Xm         175.0  37.806874              20.0   
07lVtClAEQ01iDVeaXl1         200.0   1.207884              -5.0   
0AFU6guKDt01iDVeaXl1         200.0  41.182387              21.0   
0AFU6guKDt01mfWG4vUm           0.0  46.212738              21.0   
0AFU6guKDt06y5iMXoCP         350.0   0.263554              21.0   

                      urgency_sender  
02sjTzcsaO02omVxM8Xm            25.0  
07lVtClAEQ01iDVeaXl1             4.0  
0AFU6guKDt01iDVeaXl1             4.0  
0AFU6guKDt01mfWG4vUm            25.0  
0AFU6guKDt06y5iMXoCP            25.0  

[5 rows x 110 columns]

In [6]:
y1.head()

02sjTzcsaO02omVxM8Xm    0
07lVtClAEQ01iDVeaXl1    0
0AFU6guKDt01iDVeaXl1    0
0AFU6guKDt01mfWG4vUm    0
0AFU6guKDt06y5iMXoCP    0
Name: response, dtype: int64

In [7]:
y2.head()

02sjTzcsaO02omVxM8Xm    1
07lVtClAEQ01iDVeaXl1    1
0AFU6guKDt01iDVeaXl1    1
0AFU6guKDt01mfWG4vUm    1
0AFU6guKDt06y5iMXoCP    1
Name: len_convo, dtype: int64

# TRAIN TEST SPLIT

In [36]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X.as_matrix(), y1.as_matrix(), random_state=17)

np.save(data_file_path+'X_train', X_train)
np.save(data_file_path+'X_test', X_test)
np.save(data_file_path+'y_train', y_train)
np.save(data_file_path+'y_test', y_test)

# resample
X_train, y_train = ms.oversample(X_train, y_train, .5)

# scale data
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
cols = X.columns
list(cols)
np.save(data_file_path+'cols', cols)

In [28]:
def display_importances_trees(model, cols):
    # show feature importances
    pd.options.display.float_format = '{:,.2f}'.format
    feature_df = pd.DataFrame([cols, model.feature_importances_]).T
    feature_df.columns = ['feature','coefficient']
    return feature_df.sort_values('coefficient', ascending=False)

# DECISION TREE CLASSIFIER

In [35]:
%%time

# fit model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# show metrics
y_pred = model.predict(X_test)

print("\nMETRICS")
print("Model recall: {}".format(recall_score(y_test, y_pred)))
print("Model precision: {}".format(precision_score(y_test, y_pred)))
print("Model accuracy: {}".format(model.score(X_test, y_test)))
print("Model f1: {}".format(f1_score(y_test, y_pred)))

print ("\nCONFUSION MATRIX")
print (confusion_matrix(y_test, y_pred))
print ("\nkey:")
print (" TN   FP ")
print (" FN   TP ")

# show importances
print(display_importances_trees(model, cols).head(10))


METRICS
Model recall: 0.28076923076923077
Model precision: 0.3093220338983051
Model accuracy: 0.8632278233685033
Model f1: 0.2943548387096775

CONFUSION MATRIX
[[2136  163]
 [ 187   73]]

key:
 TN   FP 
 FN   TP 
                           feature coefficient
64              len_about_receiver        0.10
59    created_day_of_year_receiver        0.09
1        first_message_day_of_year        0.05
18      created_day_of_year_sender        0.04
75            len_hobbies_receiver        0.04
70                    age_receiver        0.03
60   created_day_of_month_receiver        0.03
107                       distance        0.03
104                overlap_hobbies        0.03
4               first_message_hour        0.03
CPU times: user 451 ms, sys: 18.4 ms, total: 469 ms
Wall time: 502 ms


# RANDOM FOREST CLASSIFIER

In [11]:
%%time

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# show metrics
y_pred = model.predict(X_test)

print("\nMETRICS")
print("Model recall: {}".format(recall_score(y_test, y_pred)))
print("Model precision: {}".format(precision_score(y_test, y_pred)))
print("Model accuracy: {}".format(model.score(X_test, y_test)))

print ("\nCONFUSION MATRIX")
print (confusion_matrix(y_test, y_pred))
print ("\nkey:")
print (" TN   FP ")
print (" FN   TP ")

# show importances
print(display_importances_trees(model, X).head(10))


METRICS
Model recall: 0.09615384615384616
Model precision: 0.5952380952380952
Model accuracy: 0.9015240328253223

CONFUSION MATRIX
[[2282   17]
 [ 235   25]]

key:
 TN   FP 
 FN   TP 
                           feature coefficient
64              len_about_receiver        0.05
59    created_day_of_year_receiver        0.04
1        first_message_day_of_year        0.04
18      created_day_of_year_sender        0.03
70                    age_receiver        0.03
75            len_hobbies_receiver        0.03
60   created_day_of_month_receiver        0.02
107                       distance        0.02
0                first_message_len        0.02
23                len_about_sender        0.02
CPU times: user 308 ms, sys: 12.2 ms, total: 320 ms
Wall time: 327 ms


# GradientBoostingClassifier

In [12]:
%%time

# fit model
model = GradientBoostingClassifier(learning_rate= 0.4, 
                                   max_depth= 10, 
                                   min_samples_leaf= 2, 
                                   min_samples_split= 3, 
                                   n_estimators= 100, 
                                   subsample= 1)

# model = GradientBoostingClassifier()
model.fit(X_train, y_train)

# show metrics
y_pred = model.predict(X_test)

print("\nMETRICS")
print("Model recall: {}".format(recall_score(y_test, y_pred)))
print("Model precision: {}".format(precision_score(y_test, y_pred)))
print("Model accuracy: {}".format(model.score(X_test, y_test)))

print ("\nCONFUSION MATRIX")
print (confusion_matrix(y_test, y_pred))
print ("\nkey:")
print (" TN   FP ")
print (" FN   TP ")

# show importances
print(display_importances_trees(model, X).head(10))


METRICS
Model recall: 0.18846153846153846
Model precision: 0.5
Model accuracy: 0.8983978116451738

CONFUSION MATRIX
[[2250   49]
 [ 211   49]]

key:
 TN   FP 
 FN   TP 
                           feature coefficient
64              len_about_receiver        0.04
59    created_day_of_year_receiver        0.04
107                       distance        0.04
1        first_message_day_of_year        0.03
60   created_day_of_month_receiver        0.02
70                    age_receiver        0.02
0                first_message_len        0.02
18      created_day_of_year_sender        0.02
23                len_about_sender        0.02
4               first_message_hour        0.02
CPU times: user 43.5 s, sys: 408 ms, total: 43.9 s
Wall time: 46.8 s


# ADABOOST CLASSIFIER

In [13]:
%%time

# fit model
model = AdaBoostClassifier()
model.fit(X_train, y_train)


# show metrics
y_pred = model.predict(X_test)

print("\nMETRICS")
print("Model recall: {}".format(recall_score(y_test, y_pred)))
print("Model precision: {}".format(precision_score(y_test, y_pred)))
print("Model accuracy: {}".format(model.score(X_test, y_test)))

print ("\nCONFUSION MATRIX")
print (confusion_matrix(y_test, y_pred))
print ("\nkey:")
print (" TN   FP ")
print (" FN   TP ")

# show importances
print(display_importances_trees(model, X).head(10))


METRICS
Model recall: 0.6653846153846154
Model precision: 0.21200980392156862
Model accuracy: 0.7147323173114498

CONFUSION MATRIX
[[1656  643]
 [  87  173]]

key:
 TN   FP 
 FN   TP 
                          feature coefficient
59   created_day_of_year_receiver        0.12
1       first_message_day_of_year        0.10
18     created_day_of_year_sender        0.08
70                   age_receiver        0.06
108              urgency_receiver        0.06
53               minCost_receiver        0.04
62          has_password_receiver        0.02
48        inRelationship_receiver        0.02
93                   same_student        0.02
25           len_amenities_sender        0.02
CPU times: user 2.55 s, sys: 50.4 ms, total: 2.6 s
Wall time: 2.92 s
