## INCLUDES:

# LOGISTIC REGRESSION

# DECISION TREE CLASSIFIER

# RANDOM FOREST CLASSIFIER

# GRADIENT BOOSTING CLASSIFIER

In [26]:
import pandas as pd
import numpy as np

import my_pickle as mp
import my_resample as ms

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score

# from sklearn.model_selection import GridSearchCV

# from sklearn.model_selection import KFold
# from sklearn.metrics import roc_curve, auc
# from scipy import interp
# from random import *
# import matplotlib.pyplot as plt
# %matplotlib inline

# from sklearn.ensemble.partial_dependence import plot_partial_dependence
# from sklearn.ensemble.partial_dependence import partial_dependence

In [9]:
X = mp.unjson_it('data_X')
y = mp.unjson_it('data_y')['response']

# MAIN FN

In [27]:
def my_pipeline(model, vebose=False):
    
    # train test split
    X_train, X_test, y_train, y_test = train_test_split(X.as_matrix(), y.as_matrix(), random_state=17)

    # resample
    X_train, y_train = ms.oversample(X_train, y_train, .5)

    # scale data
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    # fit data
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    return recall_score(y_test, y_pred), precision_score(y_test, y_pred), model.score(X_test, y_test)

    if verbose:
        print("\nMETRICS")
        print("Model recall: {}".format(recall_score(y_test, y_pred)))
        print("Model precision: {}".format(precision_score(y_test, y_pred)))
        print("Model accuracy: {}".format(model.score(X_test, y_test)))

        print ("\nCONFUSION MATRIX")
        print (confusion_matrix(y_test, y_pred))
        print ("\nkey:")
        print (" TN   FP ")
        print (" FN   TP ")

        pred_all_0 = [0]*len(y_test)
        pred_all_1 = [1]*len(y_test)
        pred_50_50 = np.random.choice([0,1], size=len(y_test))
        pred_90_10 = np.random.choice([0,1], size=len(y_test), p=[.9,.1])
        
        print("\nRECALL AND ACCURACY FOR DIFFERNET MODELS")
        print("recall     \t precision   \tmodel")
        print(recall_score(y_test, y_pred), '\t',precision_score(y_test, y_pred), "my model")
        print(recall_score(y_test, pred_all_0),'\t','\t', precision_score(y_test, pred_all_0), "\t\tpredict all zero")
        print(recall_score(y_test, pred_all_1),'\t','\t', precision_score(y_test, pred_all_1), "predict all one")
        print(recall_score(y_test, pred_50_50),'\t', precision_score(y_test, pred_50_50), "predict 50-50")
        print(recall_score(y_test, pred_90_10), precision_score(y_test, pred_90_10), "predict 90-10")

# RANDOM FOREST CLASSIFIER

In [28]:
model = RandomForestClassifier(max_depth=50, max_features=None, min_samples_leaf=3, n_estimators=100, n_jobs=-1)
do_stuff(model)

feature_importances = np.argsort(model.feature_importances_)
top_n = 10
print("\nFEATURE RANKINGS")
for n in range(top_n):
    print(n+1, '\t',X.columns[feature_importances[-n-1]], '\t',sorted(model.feature_importances_)[-n-1])


METRICS
Model recall: 0.16040955631399317
Model precision: 0.42342342342342343
Model accuracy: 0.888569374550683

CONFUSION MATRIX
[[2425   64]
 [ 246   47]]

key:
 TN   FP 
 FN   TP 

RECALL AND ACCURACY FOR DIFFERNET MODELS
recall     	 precision   	model
0.160409556314 	 0.423423423423 my model
0.0 	 	 0.0 		predict all zero
1.0 	 	 0.105319913731 predict all one
0.518771331058 	 0.106741573034 predict 50-50
0.116040955631 0.114093959732 predict 90-10


/Users/gandalf/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)



FEATURE RANKINGS
1 	 len_about_receiver 	 0.0957033179665
2 	 distance 	 0.0889721461666
3 	 age_receiver 	 0.0580360146242
4 	 maxCost_receiver 	 0.0526454413219
5 	 urgency_receiver 	 0.0391853989622
6 	 urgency_sender 	 0.0382053211554
7 	 age_dif 	 0.0377325737466
8 	 maxCost_sender 	 0.0357812383137
9 	 len_about_sender 	 0.0331946526687
10 	 minCost_receiver 	 0.0319950757122


# GRADIENT BOOSTING CLASSIFIER

In [29]:
model = GradientBoostingClassifier()
do_stuff(model)

feature_importances = np.argsort(model.feature_importances_)
top_n = 10
print("\nFEATURE RANKINGS")
for n in range(top_n):
    print(n+1, '\t',X.columns[feature_importances[-n-1]], '\t',sorted(model.feature_importances_)[-n-1])


METRICS
Model recall: 0.5563139931740614
Model precision: 0.21419185282522996
Model accuracy: 0.7383177570093458

CONFUSION MATRIX
[[1891  598]
 [ 130  163]]

key:
 TN   FP 
 FN   TP 

RECALL AND ACCURACY FOR DIFFERNET MODELS
recall     	 precision   	model
0.556313993174 	 0.214191852825 my model
0.0 	 	 0.0 		predict all zero
1.0 	 	 0.105319913731 predict all one
0.481228668942 	 0.102396514161 predict 50-50
0.0648464163823 0.0703703703704 predict 90-10

FEATURE RANKINGS
1 	 urgency_receiver 	 0.102568827974
2 	 urgency_sender 	 0.080896654926
3 	 len_about_receiver 	 0.0789943268579
4 	 age_receiver 	 0.0747287291074
5 	 distance 	 0.0605902757686
6 	 isStudent_receiver 	 0.0534049651658
7 	 maxCost_receiver 	 0.0447464616228
8 	 age_dif 	 0.0392171997138
9 	 numRoommates_receiver 	 0.0328159680465
10 	 period_count_receiver 	 0.029789745294


/Users/gandalf/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


# DECISION TREE CLASSIFIER

In [30]:
model = DecisionTreeClassifier()
do_stuff(model)

feature_importances = np.argsort(model.feature_importances_)
top_n = 10
print("\nFEATURE RANKINGS")
for n in range(top_n):
    print(n+1, '\t',X.columns[feature_importances[-n-1]], '\t',sorted(model.feature_importances_)[-n-1])


METRICS
Model recall: 0.20477815699658702
Model precision: 0.21052631578947367
Model accuracy: 0.8353702372393961

CONFUSION MATRIX
[[2264  225]
 [ 233   60]]

key:
 TN   FP 
 FN   TP 

RECALL AND ACCURACY FOR DIFFERNET MODELS
recall     	 precision   	model
0.204778156997 	 0.210526315789 my model
0.0 	 	 0.0 		predict all zero
1.0 	 	 0.105319913731 predict all one
0.535836177474 	 0.115952732644 predict 50-50
0.0921501706485 0.100746268657 predict 90-10

FEATURE RANKINGS
1 	 len_about_receiver 	 0.0984110870658
2 	 distance 	 0.0894790715008
3 	 age_receiver 	 0.0558216963682
4 	 urgency_receiver 	 0.0494739584059
5 	 minCost_receiver 	 0.0445277172083
6 	 urgency_sender 	 0.0405899938056
7 	 len_about_sender 	 0.0383268092995
8 	 maxCost_sender 	 0.0377616510852
9 	 age_sender 	 0.036495401473
10 	 age_dif 	 0.0352120226206


/Users/gandalf/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


# LOGISTIC REGRESSION

In [25]:
model = LogisticRegression()
do_stuff(model)


METRICS
Model recall: 0.07167235494880546
Model precision: 0.1242603550295858
Model accuracy: 0.8490294751976994

CONFUSION MATRIX
[[2341  148]
 [ 272   21]]

key:
 TN   FP 
 FN   TP 

RECALL AND ACCURACY FOR DIFFERNET MODELS
recall     	 precision   	model
0.0716723549488 	 0.12426035503 my model
0.0 	 	 0.0 		predict all zero
1.0 	 	 0.105319913731 predict all one
0.477815699659 	 0.103934669636 predict 50-50
0.0887372013652 0.0884353741497 predict 90-10


/Users/gandalf/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
results_df = pd.DataFrame([X.columns,model.coef_[0]]).T
results_df.columns = ['feature','coefficients']
results_df['abs_val'] = results_df.coefficients.apply(abs)
results_df['sign'] = results_df.coefficients.apply(lambda s: s>0)

In [23]:
results_df.head().sort_values('abs_val', ascending=False)

feature coefficients       abs_val   sign
3      age_receiver  2.42751e-20  2.427509e-20   True
0  I_count_receiver    1.359e-20  1.358998e-20   True
1    I_count_sender  6.26409e-21  6.264091e-21   True
4        age_sender -4.63331e-21  4.633312e-21  False
2           age_dif -1.34447e-21  1.344466e-21  False

In [24]:
results_df.set_index('feature').loc['age_receiver'].sign

True

In [ ]:
def do_grid_search(X, y):
    '''
    X as 2d numpy array
    y as 1d numpy array
    
    PARAMETERS
    n_estimators: The number of trees in the forest
    criterion: gini or entropy
    max_features: The number of features to consider when looking for the best split
        If int, then consider max_features features at each split.
        If float, then max_features is a percentage and int(max_features * n_features) features are considered at each split.
        If “auto”, then max_features=sqrt(n_features).
        If “sqrt”, then max_features=sqrt(n_features) (same as “auto”).
        If “log2”, then max_features=log2(n_features).
        If None, then max_features=n_features.
    max_depth: The maximum depth of the tree
    n_jobs: The number of jobs to run in parallel for both fit and predict. If -1, then the number of jobs is set to the number of cores.
    '''
    
    # Split it up into our training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    # resample
    X_train, y_train = ms.oversample(X_train.as_matrix(), y_train.as_matrix(), .5)
    
    # Initalize our model here
    model = RandomForestClassifier()

    # Here are the params we are tuning
    param_grid = {'max_features' : [None],
                  'n_estimators' : [50,100,1000],
                  'max_depth': [50],
                  'min_samples_leaf': [3]
                  }

    # Plug in our model, params dict, and the number of jobs, then .fit()
    gs_cv = GridSearchCV(model, param_grid, n_jobs=-1).fit(X_train, y_train)

    # return the best score and the best params
    return gs_cv.best_score_, gs_cv.best_params_

In [ ]:
%%time
model = RandomForestClassifier(max_depth=50, max_features=None, min_samples_leaf=3, n_estimators=100, n_jobs=-1)
fit_model(model, X, y)

In [ ]:
%%time
n = do_grid_search(X, y)
print(n)

In [ ]:
%%time
model = LogisticRegression()
fit_model(model, X, y)

In [ ]:

print ("    Decision Tree:       ", get_scores(DecisionTreeClassifier, X_train, X_test, y_train, y_test))
print ("    Naive Bayes:         ", get_scores(MultinomialNB, X_train, X_test, y_train, y_test))

In [ ]:
# Calculate the standard deviation for feature importances across all trees

n = len(X.columns)

#importances = forest_fit.feature_importances_[:n]
importances = model.feature_importances_[:n]
std = np.std([tree.feature_importances_ for tree in model.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]
features = list(X.columns[indices])

# print("Feature ranking:")
# for f in range(n):
#     print("%d. %s (%f)" % (f + 1, features[f], importances[indices[f]]))

# Plot the feature importances of the forest
plt.figure(figsize=(16,12))
plt.title("Feature importances")
plt.bar(range(n), importances[indices], yerr=std[indices], color="r", align="edge", width = -.9)
plt.xticks(range(n), features, rotation=-75)
plt.xlim([-1, n])
plt.show()

In [ ]:
# Try modifying the number of trees, graph results
num_trees = range(5, 50, 5)
accuracies = []
for n in num_trees:
    tot = 0
    for i in range(5):
        rf = RandomForestClassifier(n_estimators=n)
        rf.fit(X_train, y_train)
        tot += rf.score(X_test, y_test)
    accuracies.append(tot / 5)
plt.plot(num_trees, accuracies)
plt.xlabel="num_trees"
plt.ylabel="accuracy"
plt.show()

In [ ]:
# Modifying the max features parameter
for nn in range(10):
    num_features = range(2, len(X.columns))
    accuracies = []
    for n in num_features:
        tot = 0
        for i in range(5):
            rf = RandomForestClassifier(max_features=n)
            rf.fit(X_train, y_train)
            tot += rf.score(X_test, y_test)
        accuracies.append(tot / 5)
    plt.plot(num_features, accuracies)
    plt.xlabel="num_features"
    plt.ylabel="accuracy"
plt.show()

In [ ]:
# Run all the other classifiers that we have learned so far in class
def get_scores(classifier, X_train, X_test, y_train, y_test, **kwargs):
    model = classifier(**kwargs)
    model.fit(X_train, y_train)
    y_predict = model.predict(X_test)
    return model.score(X_test, y_test), \
           precision_score(y_test, y_predict), \
           recall_score(y_test, y_predict)

print ("    Model,                Accuracy, Precision, Recall")
print ("    Random Forest:       ", get_scores(RandomForestClassifier, X_train, X_test, y_train, y_test, n_estimators=25, max_features=5))
print ("    Logistic Regression: ", get_scores(LogisticRegression, X_train, X_test, y_train, y_test))
print ("    Decision Tree:       ", get_scores(DecisionTreeClassifier, X_train, X_test, y_train, y_test))
print ("    Naive Bayes:         ", get_scores(MultinomialNB, X_train, X_test, y_train, y_test))

In [ ]:
def plot_roc(X, y, clf_class, title, **kwargs):
# def plot_roc(X, y, clf_class, kwargs):
    scaler = StandardScaler()
    X = scaler.fit_transform(X)
    kf = KFold(len(y), n_folds=5, shuffle=True)
    y_prob = np.zeros((len(y),2))
    mean_tpr = 0.0
    mean_fpr = np.linspace(0, 1, 100)
    all_tpr = []
    for i, (train_index, test_index) in enumerate(kf):
        X_train, X_test = X[train_index], X[test_index]
        y_train = y[train_index]
        clf = clf_class(**kwargs)
        clf.fit(X_train,y_train)
        # Predict probabilities, not classes
        y_prob[test_index] = clf.predict_proba(X_test)
        fpr, tpr, thresholds = roc_curve(y[test_index], y_prob[test_index, 1])
        mean_tpr += interp(mean_fpr, fpr, tpr)
        mean_tpr[0] = 0.0
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, lw=1, label='ROC fold %d (area = %0.2f)' % (i, roc_auc))
    mean_tpr /= len(kf)
    mean_tpr[-1] = 1.0
    mean_auc = auc(mean_fpr, mean_tpr)
    plt.plot(mean_fpr, mean_tpr, 'k--',label='Mean ROC (area = %0.2f)' % mean_auc, lw=2)

    plt.plot([0, 1], [0, 1], '--', color=(0.6, 0.6, 0.6), label='Random')
    plt.xlim([-0.05, 1.05])
    plt.ylim([-0.05, 1.05])
#     plt.xlabel('False Positive Rate')
#     plt.ylabel('True Positive Rate')
    plt.title(title + 'ROC')
    plt.legend(loc="lower right")
    plt.show()

In [ ]:
xfake, yfake = np.random.rand(100,6), np.random.randint(0,2, size=(100,))
plt.figure(figsize=(20,16))
print ("Visualize the roc curve of each model")
plot_roc(xfake, yfake, RandomForestClassifier, 'Random_Forest', n_estimators=25, max_features=5)
#plot_roc(X, y, LogisticRegression, 'Logistic_Regrssion')
#plot_roc(X, y, DecisionTreeClassifier, 'Decision_Tree')
#plot_roc(X, y, MultinomialNB, 'Naive_Bayes') error
print('\nPlotting completed.')

In [ ]:
print ("Visualize the roc curve of each model")
plot_roc(X, y, RandomForestClassifier, 'Random_Forest', n_estimators=25, max_features=5)
plot_roc(X, y, LogisticRegression, 'Logistic_Regrssion')
plot_roc(X, y, DecisionTreeClassifier, 'Decision_Tree')
#plot_roc(X, y, MultinomialNB, 'Naive_Bayes') error
print('\nPlotting completed.')